{% set name = "sparkhpc" %}
{% set version = "0.3.post4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 08869aeeb2f99f46678f0ebdeac6ccf5252efacbeb885b6dd9154568d3a84e88

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:    
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - click
    - findspark
    - python >={{ python_min }}
    - setuptools

test:
  requires:
    - python {{ python_min }}
  imports:
    - sparkhpc

about:
  home: http://sparkhpc.readthedocs.io
  license: MIT  
  license_file: LICENSE
  summary: spark deployment on hpc resources made easy
  doc_url: https://sparkhpc.readthedocs.io/en/latest/
  dev_url: https://github.com/rokroskar/sparkhpc

extra:
  recipe-maintainers:
    - dirmeier
