travis:
  secure:
    BINSTAR_TOKEN: H783PPcRS2XpHGhFfFsFonaPdnT9GDPW5wXyOsJXuJ7IrR0iYKQzoiBcVw4jIhpmchCq8KJVUT/rXXldx/aJXwc82U0imQK+W1xlpo3zOCRgfplEWQcL7R3SmpyGjBFaSU5LwK6s2v6koECKX1bHZfaK3baCUerpF8OmzHCgJyku5MhI7Yj0Hw9UkvTM6miy3V+y/5aei/SBLyKLCf6utzndoifQHpURIXkDCmXsvVDR6xx64brb6cPJGEK1oegehJSe10/k5NSV1xUWObDFOyMa3eEcixK63sIcqV5UrDfSXhSbW5Oi4G7EsmzEcmgQGliaj7/1179BN+YJYkyHbk/kp/Ctr4Yn89o9siwzPC+60qTy7a+d5sDrrU5p7VyFMKbnFJ5OEBp7FcGZlq1DrNfp03rM1efL1MdxJ9bfSNvQ5ArMD3LXInuIfnSb0NKQ0AFhjlYQQbhySE1otho5oKbf2cd5VR1x/QAJwZh1CyrLyjwvTOvs8tYUn6GNkff/vjys6Zl54S0jKpoC4xzKcjDecE8bhy83RL/8tlyBpE5IaUXCraqm5/Cie3yuyH1S1+jnT74+RLC1XB55InPN3ergqCLGTtaKtrhmpk0CQk8zvF3k0aoXuetPT4x7oa4gWeoC+4PAtTyj4s6LsbKNvnpfKXrAGTSSzmqnyce9v+I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
